/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab12;

import java.awt.Component;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JComponent;

/**
 *
 * @author denis
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_CtrlPN = new javax.swing.JPanel();
        LB_CtrlPanel = new javax.swing.JLabel();
        TB_CompName = new javax.swing.JTextField();
        TB_CompX = new javax.swing.JTextField();
        TB_CompY = new javax.swing.JTextField();
        LB_CompName = new javax.swing.JLabel();
        LB_XPos = new javax.swing.JLabel();
        LB_YPos = new javax.swing.JLabel();
        BTN_Draw = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        PN_DesignPN = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_CtrlPanel.setText("Control Panel");

        TB_CompX.setName(""); // NOI18N

        LB_CompName.setText("Component Name");

        LB_XPos.setText("X Position");

        LB_YPos.setText("Y Position");

        BTN_Draw.setText("Draw");
        BTN_Draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DrawActionPerformed(evt);
            }
        });

        jTextField1.setText("Text For Component");

        javax.swing.GroupLayout PN_CtrlPNLayout = new javax.swing.GroupLayout(PN_CtrlPN);
        PN_CtrlPN.setLayout(PN_CtrlPNLayout);
        PN_CtrlPNLayout.setHorizontalGroup(
            PN_CtrlPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_CtrlPNLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(LB_CompName)
                .addGap(84, 84, 84)
                .addComponent(LB_XPos)
                .addGap(59, 59, 59)
                .addComponent(LB_YPos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PN_CtrlPNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_CtrlPanel)
                .addGap(32, 32, 32)
                .addGroup(PN_CtrlPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(TB_CompName))
                .addGap(18, 18, 18)
                .addComponent(TB_CompX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TB_CompY, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_Draw)
                .addContainerGap())
        );
        PN_CtrlPNLayout.setVerticalGroup(
            PN_CtrlPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_CtrlPNLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(PN_CtrlPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_CompName)
                    .addComponent(LB_XPos)
                    .addComponent(LB_YPos))
                .addGroup(PN_CtrlPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN_CtrlPNLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PN_CtrlPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_CtrlPanel)
                            .addComponent(TB_CompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TB_CompX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TB_CompY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PN_CtrlPNLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(BTN_Draw)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PN_DesignPNLayout = new javax.swing.GroupLayout(PN_DesignPN);
        PN_DesignPN.setLayout(PN_DesignPNLayout);
        PN_DesignPNLayout.setHorizontalGroup(
            PN_DesignPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        PN_DesignPNLayout.setVerticalGroup(
            PN_DesignPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_CtrlPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PN_DesignPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PN_CtrlPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PN_DesignPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_DrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DrawActionPerformed
        // TODO add your handling code here:
        Class c;
        try {
            c = Class.forName(TB_CompName.getText());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Did not find component", "Component not found", JOptionPane.INFORMATION_MESSAGE);;
            return;
        }
        
        Class cls[] = new Class[] { String.class };
        Constructor constructor = null;
        try {
            constructor = c.getConstructor(cls);
            JComponent comp = (JComponent) c.getDeclaredConstructor(cls).newInstance(jTextField1.getText());
            
            comp.setLocation(Integer.parseInt(TB_CompX.getText()), Integer.parseInt(TB_CompY.getText()));
            comp.setVisible(true);
            PN_DesignPN.add(comp);
            
           
        } catch (NoSuchMethodException ex) {
            
            try {
                JComponent comp = (JComponent) c.getDeclaredConstructor().newInstance();
                
                comp.setVisible(true);
                comp.setLocation(Integer.parseInt(TB_CompX.getText()), Integer.parseInt(TB_CompY.getText()));
                PN_DesignPN.add(comp);
                
            
            } catch (NoSuchMethodException ex1) {
                System.out.println(ex1.getMessage());
            } catch (InstantiationException ex1) {
                System.out.println(ex1.getMessage());
            } catch (IllegalAccessException ex1) {
                System.out.println(ex1.getMessage());
            } catch (IllegalArgumentException ex1) {
                System.out.println(ex1.getMessage());
            } catch (InvocationTargetException ex1) {
                System.out.println(ex1.getMessage());
            }
            
        } catch (SecurityException ex) {
                System.out.println(ex.getMessage());
        } catch (InstantiationException ex) {
                System.out.println(ex.getMessage());
        } catch (IllegalAccessException ex) {
                System.out.println(ex.getMessage());
        } catch (IllegalArgumentException ex) {
                System.out.println(ex.getMessage());
        } catch (InvocationTargetException ex) {
                System.out.println(ex.getMessage());
        }
        
        PN_DesignPN.validate();
        PN_DesignPN.repaint();
        
        for(Component cm : PN_DesignPN.getComponents())
        {
            System.out.println(cm.toString());
        }
        
        //pur si simplu nu vrea sa deseneze componentele noi adaugate. Nu a desenat nici un component hardcodat
        //Nu inteleg de ce
        
    }//GEN-LAST:event_BTN_DrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Draw;
    private javax.swing.JLabel LB_CompName;
    private javax.swing.JLabel LB_CtrlPanel;
    private javax.swing.JLabel LB_XPos;
    private javax.swing.JLabel LB_YPos;
    private javax.swing.JPanel PN_CtrlPN;
    private javax.swing.JPanel PN_DesignPN;
    private javax.swing.JTextField TB_CompName;
    private javax.swing.JTextField TB_CompX;
    private javax.swing.JTextField TB_CompY;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
